### PR TITLE
fix: change prefix format and pass New Relic sink

### PR DESCRIPTION
**Pull request by peter-rr**
Change prefix format for metric name and pass New Relic specific sink when creating a new recorder instance.

Relates to #841

### CODE REVIEW

**Review by smoya — APPROVED** [review]
There is one thing. You can't leave the NewRelicSink there since tests will try to send metrics over it. We should find the way to, in tests, just print metrics out over stdout or discard them.

**Review by smoya — CHANGES_REQUESTED** [review]
There is one thing. You can't leave the NewRelicSink there since tests will try to send metrics over it. We should find the way to, in tests, just print metrics out over stdout or discard them.

**Comment by peter-rr** [comment]
> There is one thing. You can't leave the NewRelicSink there since tests will try to send metrics over it. We should find the way to, in tests, just print metrics out over stdout or discard them.

Should we then go back to the `StdOutSink` and only use `NewRelicSink` for our own tests until we find a better solution?

**Comment by smoya** [comment]
> > There is one thing. You can't leave the NewRelicSink there since tests will try to send metrics over it. We should find the way to, in tests, just print metrics out over stdout or discard them.
> 
> Should we then go back to the `StdOutSink` and only use `NewRelicSink` for our own tests until we find a better solution?

Yes, I do. BTW, any idea on how to make that possible?

**Comment by peter-rr** [comment]
> BTW, any idea on how to make that possible?

I guess we could print a brief message over stdout with the metrics sent, just to test we are actually sending them regardless the sink we're using. And then only running the tests containing all the information about the metrics when executing the tests for an specific sink like New Relic. Does it make sense for you?

**Comment by peter-rr** [comment]
> BTW, any idea on how to make that possible?

Ok, I see you've already solved it [here](https://github.com/smoya/cli/blob/1994f4da7445a9d6c7f7d0662d03ce0cc6845fc1/src/base.ts#L6
) 👍

**Comment by smoya** [comment]
Closing in favor of https://github.com/smoya/cli/pull/2

**Pull request closed without merging**
